### ISSUE TITLE
Show basic controls with invalid calibration

### ISSUE THREAD

**Issue by hastarin** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#258]
### Description

If the map times out, or for whatever reason I get:
> Invalid calibration, please check your configuration.

Sadly I loose ANY control of the vacuum via the card at that point and can't return it to the dock, stop, start, etc

### Solution

Still provide basic controls when calibration is invalid and just exclude the map and features that require calibration.

**Comment by hastarin** [comment]
Actually I found out my vacuum was offline and once online basic controls became available.

So perhaps just adding an extra message when it's offline to indicate why the basic controls aren't available is what I'm after.

**Comment by fi-sch** [comment]
I am experiencing a similar issue. I did not search for a root cause yet, however.
I think that it may be caused by disabling auto_updates for [Xiaomi Cloud Map Extractor](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), as I did not experience this issue before changing this.

**Comment by PiotrMachowski** [comment]
Since `v2.0.9` all map is visible even with invalid calibration
