### ISSUE TITLE
Xiaomi STYJ02YM

### ISSUE THREAD

**Issue by JeedHome44** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#38]
Hello,
I try to use your github with Xiaomi STYJ02YM but this vacuum dont have goto_target but have a clean_target.
Can you adapt the files so that it also works with the STY?
Thank you

**Comment by PiotrMachowski** [comment]
Hi, could you specify what parameters does clean_target require?

**Comment by Heracles44** [comment]
I don’t know.
I install this GitHub 3 days ago.
https://github.com/nqkdev/home-assistant-vacuum-styj02ym

**Comment by Heracles44** [comment]
Sorry it’s clean_point and clean_zone with this GitHub:
https://github.com/nqkdev/home-assistant-vacuum-styj02ym

**Comment by Heracles44** [comment]
I found!!!! point 0, 0 is the base! 1, 0 = 1 meter on the right. 0, 1 = 1 meter at the top. and so you have to do -1, -1 to make 1 meter down and 1 meter to the left! More than doing the zones!

**Comment by tromarek1** [comment]
I have tried to call different service in JavaScript code. But with no effect. 
`
vacuumGoToPoint(debug) {
        const mapPos = this.convertMapToVacuumCoordinates(this.currPoint.x, this.currPoint.y);
        if (debug && this._config.debug) {
            alert(JSON.stringify([mapPos.x, mapPos.y]));
        } else {
            this._hass.callService("vacuum", "xiaomi_clean_point", {
                entity_id: "vacuum.bambo",
                point: [mapPos.x, mapPos.y]
            }).then(() => this.showToast());
            

        }
    }
`
In developer tools I send **vacuum.xiaomi_clean_point** service with service data:
`entity_id: vacuum.bambo
point: [0,1]`
And it's working. So what I should do?

**Comment by PiotrMachowski** [comment]
@tromarek1 the problem might be with coordinates. Try enabling debug mode and check sent coordinates. It is possible that they are out of range. You can recalibrate a map to address this problem.

**Comment by tromarek1** [comment]
Coordinates are okay. 
![image](https://user-images.githubusercontent.com/5338931/93416714-9f5aa980-f8a6-11ea-980f-b0a5b3d078ed.png)

**Comment by PiotrMachowski** [comment]
Installing via HACS is not a preferred way of installation 9f you want to modify code, as it caches files. Copy modified files outside of HACS folder, update resources, clear cache and try again. This might solve your problem

**Comment by tromarek1** [comment]
Zmieniłem lokalizację i dodałem do pliku lovelace_resources this:
```
{
    "data": {
        "items": [
            {
                "type": "module",
                "url": "/local/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js"
            }
        ]
    },
    "key": "lovelace_resources",
    "version": 1
}
```

And that is what happened:
![image](https://user-images.githubusercontent.com/5338931/93418535-ee0a4280-f8aa-11ea-8a89-af46ed7871f9.png)

**Comment by tromarek1** [comment]
Ok. Now it's working. Thanks!

**Comment by tromarek1** [comment]
But now what should I do to send not rounded position?

**Comment by PiotrMachowski** [comment]
You can remove `Math.round` in methods `convertMapToVacuumRect` and `convertVacuumToMapCoordinates` and it should work.

**Comment by StankAnt** [comment]
@tromarek1 @JeedHome44 Hey, have you finished with styj02ym coordinates calibration? Could you please share your config and map, as I have some issues with the map and cant understand the issue, i'm wanna to compare them. Thanks!

**Comment by tromarek1** [comment]
> @tromarek1 @JeedHome44 Hey, have you finished with styj02ym coordinates calibration? Could you please share your config and map, as I have some issues with the map and cant understand the issue, i'm wanna to compare them. Thanks!

Check out my GitHub project for styj02ym and download it instead of PiotrMachowski interactive vacuum map card project.

**Comment by sheminasalam** [comment]
Hi I am facing some issues with my new vacuum MODEL: viomi.vacuum.v10. I have integrated  it with HA using the STYJ02YM which works fine except the services vacuum.xiaomi_clean_point and vacuum.xiaomi_clean_zone. In the developer mode I have called vacuum.xiaomi_clean_point with the data 
```entity_id: vacuum.robot_vacuum
point: [1,-1]``` and instead of cleaning that point, the robovac executed cleaning a zone of size 3 square meters. When I gave the same command again, the robot lost all its sense of direction and in the live map I could see the charging point also displaced to a different room. Any ideas

**Comment by carvalr** [comment]
@tromarek1, your card has worked like a charm for me. I had some headaches figuring out how to get the coordinates and the calibration points, but everything is working perfectly.

For those who want to set up this vacuum using this card, a lot of effort is required, especially about getting each zone coordinates. In order to help with this process, I would recommend [this video](https://www.youtube.com/watch?v=3Z6sEqVC6pQ). You will need patience and a measuring tape (or to try by yourself setting values you believe are correct), there is no other way.

I had to set values to the service [vacuum.xiaomi_clean_zone] and check the result in the Mi Home app, as many others have already suggested here. The result was like following:
# [[right, end, left, start]]
#Full map [[-4.66, -14.3, 4, 0.4]]
# HA Full Map [[-7, -14.3, 5.2, 0.5]]
#Laundry [[0.4, -1, -3.25, 0.3]],
#Kitchen [[2.90, -3, -0.54, -1.04]],

After getting coordinates of each part of my house another headache was to figure out how to set the coordinates of STYJ02YM to this card. I have used this guide and the [Excel file template](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/wiki/Map-calibration-in-FloleVac) within it.
Using the Excel template file it was not possible to get the coordinates by using the existing formula. So I pasted my coordinates besides it and I changed it manually.
![gitExcel](https://user-images.githubusercontent.com/74059823/112144209-a943c900-8bb7-11eb-97d4-9f263a762b68.PNG)

Activate the option "debug: true" in the card to see if the calibration points are exactly where you want them.
![gitmap](https://user-images.githubusercontent.com/74059823/112144215-a9dc5f80-8bb7-11eb-8d54-d4f54a6dfbc5.PNG)

That's it. Done.

**Comment by ivojed** [comment]
Hi Guys,

please can you help me with integration "xiaomi_clean_zone" into map card? 

I got error for zoned cleanup:
 _extra keys not allowed @ data['params']_

and for zones:
_None @ data['zone'][0]_

Thank you so much.

```
   vacuumStartZonedCleanup(debug) {
        const zone = [];
        for (const rect of this.rectangles) {
            zone.push(this.convertMapToVacuumRect(rect, this.vacuumZonedCleanupRepeats));
        }
        if (debug && this._config.debug) {
            alert(JSON.stringify(zone));
        } else {
            this._hass.callService(this.service_domain, "xiaomi_clean_zone", {
                entity_id: this._config.entity,
                params: zone
            }).then(() => this.showToast());
        }
    }



 vacuumStartPreselectedZonesCleanup(debug) {        const zone = [];
        for (let i = 0; i < this.selectedZones.length; i++) {
            const selectedZone = this.selectedZones[i];
            const preselectedZone = this._config.zones[selectedZone];
            for (const rect of preselectedZone) {
                zone.push([rect[0], rect[1], rect[2], rect[3], this.vacuumZonedCleanupRepeats])
            }
        }
        if (debug && this._config.debug) {
            alert(JSON.stringify(zone));
        } else {
            this._hass.callService(this.service_domain, "xiaomi_clean_zone", {
                entity_id: this._config.entity,
                zone: zone
             }).then(() => this.showToast());
        }
    }

```

**Comment by carvalr** [comment]
@ivojed you’d better paste the code of your card yaml instead of card methods.

**Comment by ivojed** [comment]
Ok, but there is different service.. Default called services  is  "send_command" with parameter command "app_zoned_clean" and i need  change  used service to  "xiaomi_clean_zone"..
```
  - type: 'custom:xiaomi-vacuum-map-card'
        entity: vacuum.xiaomi_vacuum_cleaner_styj02ym
        map_image: /hacsfiles/lovelace-xiaomi-vacuum-map-card/vacuum.png
        debug: false
        calibration_points:
          - vacuum:
              x: 25500
              'y': 25500
            map:
              x: 466
              'y': 1889
          - vacuum:
              x: 26500
              'y': 26500
            map:
              x: 730
              'y': 1625
          - vacuum:
              x: 25500
              'y': 26500
            map:
              x: 466
              'y': 1625
```

**Comment by carvalr** [comment]
@ivojed, use the card provided by [tromarek1 ](https://github.com/tromarek1/-lovelace-xiaomi-styj02ym-vacuum-map-card), as described two posts before yours. This card was adjusted to work with STYJ02YM. This is working perfectly well for me, except for the issue #100.

**Comment by ldoench** [comment]
Is there a good guide, how to acquire the calibration points? 
Because flolevac does not support the STYJ02YM, as well as the Xiaomi Cloud Map Extractor ([Issue #23](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/23) )

**Comment by carvalr** [comment]
@ldoench take a look in my comment. I was able to make the calibration points with a lot of work, but now everything works perfectly even with Alexa commands to clean specific room by combined use with NodeRED.

https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/38#issuecomment-804852643
