### ISSUE TITLE
Request: multi-level maps 

### ISSUE THREAD

**Issue by bcameron21** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#50]
The new firmware is being rolled out with multi-level maps. Would it be possible to enable this on the card somehow?

**Comment by markrennie71** [comment]
Multi level? Which versions of the vacuum will have this please?

**Comment by r3dsouza** [comment]
I would +1 this request. 

I have an S5 Max and it supports multi-level maps. I believe the new firmware brings multi-level maps to S5 Max, S6, S6 MaxV and S6 Pure.

**Comment by PiotrMachowski** [comment]
It requires a whole card to be rewritten. I have already started it, but it's not easy thing, so it's constantly pushed down on my TODO list.
For now you can use 2 instances of this card with https://github.com/bramkragten/swipe-card

**Comment by r3dsouza** [comment]
Thanks for considering this feature. I am currently using a simple implementation using vertical stack with 3 cards - card 1 with an input_select entity that allows selecting the floor level, and 2 conditional cards with the interactive map entities - one for each floor. Each of the 2 conditional cards only shows the corresponding floor map card based on the level selected. I will definitely try the swipe-card.

The one thing that I do struggle with and would like some way of implementing is to be able to somehow inform the vacuum to switch to the right map when I switch between floor maps. Currently, I have to either do this in the Xiaomi home app or the other way is to trigger the vacuum to clean momentarily just so that it re-positions itself and automatically switches to the correct floor map, then stopping the cleaning in order to then start using the features of the interactive card like, goto target, zone cleaning and zones. It is a minor annoyance to be honest, but would be great to find a solution that does not need a workaround.

**Comment by Clem-** [comment]
> @r3dsouza
> Each of the 2 conditional cards only shows the corresponding floor map card based on the level selected. I will definitely try the swipe-card.

Hi, I was looking for a way to deal with multiple map. Your workaround is pretty smart!
I was wondering though how you managed to show the corresponding floor map as mentioned?

I am currently using `Xiaomi Cloud Map Extractor` and it only shows the map selected in the Mi Home app.

Thanks !

**Comment by r3dsouza** [comment]
@Clem- Thanks for letting me know. I wasn't aware of the `Xiaomi Cloud Map Extractor`. This is actually really great. I have been playing with in yesterday and added a comment to an existing enhancement request #62. Basically, if the functionality where the card is able to use the `rooms` attribute of the extractor for it's zones, this would in essence allow for multi-level map viewing, zone cleaning, etc.

**Comment by hfcheng66** [comment]
First thanks @PiotrMachowski for the excellent work! 
I am using the map extractor and this map card for my S5Max. It works great for one map. Could you point me on any guide that how to use swipe card so it works for multi maps?

@r3dsouza could you share your setup to solve the multi maps? do you need to setup multi cameras too?

Thanks.

**Comment by PiotrMachowski** [comment]
Handled in v2.0.0
