### ISSUE TITLE
Feature Request: Ability to define coordinates of zones as template

### ISSUE THREAD

**Issue by jacekpaszkowski** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#72]
I think it would be useful to have an option to define list of coordinates element of configuration. eg. sensor, variable, input_text. Then reuse it in frontend.

I use ValetudoRE, zones are defined there. I also would like to be able to define name of the zone on the map, then this name could be passed as service parameter.

Would it be possible?

**Comment by jacekpaszkowski** [comment]
My example sersor data for forbidden zones could be:
```yaml
areas: 
- - all
  - - - 25110
      - 19057
      - 35388
      - 27625
      - 1
- - bathroom
  - - - 30752
      - 24896
      - 32411
      - 27549
      - 2
- - hall
  - - - 29810
      - 23798
      - 32560
      - 25080
      - 2
    - - 28081
      - 22729
      - 29793
      - 27673
      - 2
- - kitchen
  - - - 27795
      - 19119
      - 29778
      - 22968
      - 2
- - salon
  - - - 25122
      - 19089
      - 28440
      - 25946
      - 2
- - room
  - - - 32373
      - 23335
      - 35393
      - 27623
      - 2
- - bedroom
  - - - 30571
      - 19716
      - 35355
      - 23800
      - 2
```

**Comment by PiotrMachowski** [comment]
I plan to implement it, but configuration will probably be different

**Comment by jacekpaszkowski** [comment]
@PiotrMachowski great to hear this :) thank you

**Comment by raduparvan0** [comment]
You're script is awesome but is any way to define the zones of vacuum with buttons? Without the map?
I have 10 zones in my house but is very difficult for me to define them in the map because the child pressed on vacuum buttons and the map reseted every week, so I have to make the calibration again and again.
I want to create a lovelace where I can select the rooms selecting the buttons, than clean.
Is really helpful for me to do that because I can copy the zones from flolevac than paste them in configuration. 
Thanks,

**Comment by PiotrMachowski** [comment]
@raduparvan0 You can do it in a plain HA:
https://www.home-assistant.io/integrations/xiaomi_miio/#service-xiaomi_miiovacuum_clean_zone
https://www.home-assistant.io/lovelace/button/

**Comment by raduparvan0** [comment]
Thank you!
Just i discovered you're cloud map extractor that is very useful.

**Comment by PiotrMachowski** [comment]
Handled in v2.0.0
