### ISSUE TITLE
Add lawn_mower entity

### ISSUE THREAD

**Issue by S1M8N** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#757]
### Description

Hello,

You think it's possible to add the possibilities to use lawn_mower entites ?

### Solution

"entity: lawn_mower.xxxxxx"

**Comment by PiotrMachowski** [comment]
Does your lawn mower provide a map in HA?

**Comment by S1M8N** [comment]
some model yes other no but mine has no map

**Comment by PiotrMachowski** [comment]
The map is a core feature of this card, do you still need it if your lawn mower doesn't provide it?

**Comment by S1M8N** [comment]
I think if it's possible to have picture to replace map like this card  : custom:xiaomi-vacuum-card would have been very nice.

I made this request here because the other custom card have had the laste update 4 years ago.

**Comment by PiotrMachowski** [comment]
> like this card : custom:xiaomi-vacuum-card

This card is really simple to create on your own using built-in picture-elements card:
https://github.com/PiotrMachowski/Home-Assistant-picture-elements-Xiaomi-Vacuum-black/blob/master/vacuum_card.yaml

**Comment by S1M8N** [comment]
Yes sure, just I think it is a good idea to add the possibility tu use lawn mower because any vacuum card propose that while the operation with lawn mower and vacuum is realy similar...

**Comment by PiotrMachowski** [comment]
Technically at this moment you can just provide a lawn mover entity instead of vacuum entity and configure icons/tiles manualy. What would need to be done is the automatic generation of card's configuration, which is integration-specific, so I will close this issue. If you would like to make a config for your integration please create a "Request support for a new vacuum platform" issue
